#!/bin/sh

echo installetion 3te


string=`g++ -print-search-dirs`

IFS=':' read -r a second a fourth a <<-_EOF_
$string
_EOF_

echo $second


#mkdir /usr/include/3te

cp ./*.h /usr/include/3te/
cp ./build/lib3te.a $second

echo "files installed to /usr/include/3te/"
echo ./*.h
echo "lib3te.a installed to $second"


echo "
#!/bin/sh

echo updating 3te

string=`g++ -print-search-dirs`

IFS=':' read -r a second a fourth a <<-_EOF_
$string
_EOF_

echo $second


cp ./*.h /usr/include/3te/
cp ./build/lib3te.a $second


echo files installed to /usr/include/3te/
echo ./*.h
echo lib3te.a installed to $second" >> update

chmod +x ./update
